### ISSUE TITLE
Incorrect type used for hid_t in NDFileHDF5::createDataset

### ISSUE THREAD

**Issue by ajgdls** [areaDetector/ADCore#116]
Whilst testing against the HDF5 library version 1.9.222 it was discovered that some attributes were not appended to datasets as expected.  In the createDataset method an integer is used for returning the hid_t type, which would work for earlier versions of the HDF5 library but is not correct and now fails to work, returning 0 for datasets that actually have valid IDs.  The integer type used for returning a dataset ID in this method should be replaced by the hid_t type.

**Comment by ulrikpedersen** [comment]
Fixed by Alan in 041366d. Closing ticket.
