### ISSUE TITLE
v4-plugin branch doesn't compile on win32 environment

### ISSUE THREAD

**Issue by ajgdls** [areaDetector/ADCore#117]
An error is raised, "cannot allocate an array of constant size 0" when compiling under Microsoft VS 2010.  The error occurs in ADApp/ntndArrayConverterSrc/ntndArrayConverter.cpp fromStringAttribute method.  I'll update the method to malloc the memory required, as you cannot allocate an array of unknown size in C++ (depending on how strict the compiler is).

**Comment by ulrikpedersen** [comment]
I think this works for us now... Can we close this Alan?

**Comment by ajgdls** [comment]
I have been running on win32 for a while with this plugin, so I'm happy that this is working.

**Comment by ulrikpedersen** [comment]
Thanks Alan. Closing issue.
