### ISSUE TITLE
HDF5 file writer documentation update

### ISSUE THREAD

**Issue by ulrikpedersen** [areaDetector/ADCore#126]
I've spotted missing documentation for a few new(ish) PVs in the HDF5 file writer:

* LazyOpen
* TempSuffix
* CreateDirectory

**Comment by MarkRivers** [comment]
I don't think those should be documented in the HDF5 file writer documentation.  Those are base class PVs that apply to all (or most) file writers, and so should be documented in the base class.  In fact they are documented in the asynNDArrayDriver base class.
http://cars9.uchicago.edu/software/epics/areaDetectorDoc.html#asynNDArrayDriver

**Comment by ulrikpedersen** [comment]
I'm just not having a good start after the holidays... I'm going home now.

Closing ticket (wontfix).
