### ISSUE TITLE
NDAttribute sourceType is not initialised.

### ISSUE THREAD

**Issue by ajgdls** [areaDetector/ADCore#130]
I think this is a problem (sorry if I misunderstand what should be happening in the NDAttribute class)...

In the NDAttribute constructor that takes a NDAttrSource_t sourceType parameter, the source type is not stored as a member of the class.  The string representation of the source is correctly allocated but there is no line that looks like

this->sourceType = sourceType;

or 

sourceType(sourceType)

in the constructor.

If the getSourceInfo method is later called then the pointer to NDAttrSource_t appears to be filled with junk as the sourceType member variable is uninitialised.

**Comment by MarkRivers** [comment]
Fixed in pull request #131.
