### ISSUE TITLE
commonDriverMakefile typo

### ISSUE THREAD

**Issue by mdavidsaver** [areaDetector/ADCore#231]
I noticed the following in ADApp/commonDriverMakefile and ADApp/commonLibraryMakefile

```
    ifdef JPEG_LIB
      hdf5_DIR     = $(jpeg_LIB)
      PROD_LIBS     += jpeg
    else
      PROD_SYS_LIBS += jpeg
    endif
```

The line ```hdf5_DIR     = $(jpeg_LIB)``` looks a bit odd.

https://github.com/areaDetector/ADCore/blob/master/ADApp/commonDriverMakefile#L59

**Comment by MarkRivers** [comment]
Good spot, thanks.  Fixed on master and Remove_MAX_ATTRIBUTE_STRING_SIZE branches.
