### ISSUE TITLE
Release 2-6

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCore#243]
I would like to release R2-6 soon.  It will require asyn R4-31, so that needs to be released first.

Are there any other things that need to be done before R2-6 is released?

**Comment by ulrikpedersen** [comment]
I would have liked to close out #203 but unfortunately the HDF Group have not yet released the fix. I guess that leaves us in the same place as in release 2-5.

I see you've been impressively organised and closed out all the [Release 2-6 milestones](https://github.com/areaDetector/ADCore/milestone/3?closed=1) Thanks! :+1: 

I can't think of anything else that we would want included for 2-6.

**Comment by MarkRivers** [comment]
Closed via R2-6 tag.
