### ISSUE TITLE
../NDPluginDriver.cpp:60:34 error: 'setTimeStamp' was not declared in this scope

### ISSUE THREAD

**Issue by dmichel76** [areaDetector/ADCore#27]
Just tried to build the latest code on Ubuntu 12.04 and got this error:

../NDPluginDriver.cpp: In member function 'virtual void NDPluginDriver::processCallBacks(NDArray*)':
../NDPluginDriver.cpp:60:34 error: 'setTimeStamp' was not declared in this scope

**Comment by MarkRivers** [comment]
Original problem was the use of an old version of asyn.  Other problems appear to be solved as well.
