### ISSUE TITLE
Coveralls problem

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/ADCore#285]
It looks like the [Coveralls build](https://coveralls.io/github/areaDetector/ADCore) is not working correctly?  There is no data for builds after #765?  Anyone know what could be wrong?

**Comment by GDYendell** [comment]
Looks like the "USR_CXXFLAGS_Linux=--coverage" flags were taken out here as part of unrelated refactoring.

**Comment by MarkRivers** [comment]
Thanks for finding that.  I have added those flags in install-packages.sh and pushed to Github.  The Corveralls build is now working again.
