### ISSUE TITLE
remove #ifdef HAVE_PVAPI blocks from NDPluginColorConvert

### ISSUE THREAD

**Issue by arvinderpalaha** [areaDetector/ADCore#322]
As the PvApi library from prosilica is now in ADProsilica and not in ADCore, shouldn't the #ifdef HAVE_PVAPI ... #endif blocks be removed from NDPluginColorConvert (h/cpp) as this condition will never be fulfilled?

**Comment by MarkRivers** [comment]
Fixed, removed code that used HAVE_PVAPI.
