### ISSUE TITLE
Chunking issue in HDF5AttributeDataset

### ISSUE THREAD

**Issue by MattTaylorDLS** [areaDetector/ADCore#377]
@ajgdls and I have found an issue in the NDFileHDF5AttributeDataset class.

Currently, within the configureDimsFromDataset() function, if it's a multiframe, it sets the chunk_ array to values from the user_chunking array, index to index. This is the wrong way round and it should be setting them in reverse order, as when the chunk_ array is used, it is expected the extra dimensions are at the start of the array. 

The fix for this is within the for loop in the if (multiframe), to instead of setting:
this->chunk_[i]       = user_chunking[i];

It should be set like:
this->chunk_[i]       = user_chunking[(extradims-1)-i];

[Currently, line 289 on master]

**Comment by MarkRivers** [comment]
I have made this change and pushed to Github.
