### ISSUE TITLE
Implement bayer to rgb colour conversion

### ISSUE THREAD

**Issue by arvinderpalaha** [areaDetector/ADCore#399]
Since moving to ADCore from areaDetector, the proprietary prosilica PV library is no longer included that performed the bayer to RGB colour conversion. This should be introduced in the NDPluginColorConvert code.

**Comment by arvinderpalaha** [comment]
Hi @MarkRivers, I'm currently working on this for Diamond, and intend to push this upstream once I have tested different scenarios.

**Comment by MarkRivers** [comment]
What code are you using for the Bayer to RGB conversion? Is it open source?

ADProsilica and ADPointGrey do make this available via the vendor SDKs but it would be great to have a general solution in NDPluginColorConvert.

**Comment by arvinderpalaha** [comment]
Hi Mark,


I did start to look at the openCV code, but I felt it might be simpler to implement a simple nearest neighbours style approach directly without adding a dependency to ADCore.


I agree, having a way to use the bayer colour option for any camera while using ADCore would be great.


Best regards,


Arvinder Palaha
Beamline Control Systems
DH G.63
T: +44-(0)1235-77-8137
E: arvinder.palaha@diamond.ac.uk

________________________________

**Comment by MarkRivers** [comment]
Have you looked at the code in caQtDM for color conversion?  Anton Mezger  told me that it now supports Bayer decoding.  I took a look and the code is here I believe:
https://github.com/caqtdm/caqtdm/blob/Development/caQtDM_QtControls/src/cacamera.cpp

**Comment by arvinderpalaha** [comment]
I'll take a look, thanks!

**Comment by MarkRivers** [comment]
Closed via #405
