### ISSUE TITLE
NDPluginProcess unexpected behaviour when flat field correction enabled 

### ISSUE THREAD

**Issue by mp49** [areaDetector/ADCore#440]
The code responsible for flat field correction in NDPluginProcess is:

```
if (flatField) {
            if (flatField[i] != 0.) 
                value *= scaleFlatField / flatField[i];
            else
                value = scaleFlatField;
        }
```

If an element of the flat field correction array is zero, the value gets changed to the scaleFlatField value.

Possibly a more correct behavior is to leave the value unchanged (ie. set value = value, or remove the else clause).

**Comment by MarkRivers** [comment]
I suggest just removing the else clause.  The idea of scaleFlatField is that it will generally be used to produce a value that is similar in magnitude to the original value, i.e. something like the average of the the flatfield.  So we don't want to multiply by that if flatField[i]==0.
