### ISSUE TITLE
CONST attributes in attributes.xml file?

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADCore#478]
Motivated by trying to write the bluesky RunEngine metadata into the NDAttributes [here](https://github.com/BCDA-APS/bdp_controls/issues/32#issuecomment-1098355595), is it possible to add a CONST type of attribute?

One use would be for a client to inject a specific metadata key:value to be found in an image's attributes (such as PVA).  If the key:value is not matched, the client can skip processing of that image.

**Comment by prjemian** [comment]
Thank you!

**Comment by MarkRivers** [comment]
I changed the code a bit after the merge. The attributes did not have the correct attribute type, so that report() was giving misleading information.
