### ISSUE TITLE
NDPluginProcess scale and offset

### ISSUE THREAD

**Issue by domitto** [areaDetector/ADCore#500]
Hi Mark,
I was trying to use the NDPluginProcess and had issues with the offset portion not working as expected.
The documentation mentions that the processing step consists of:
Array = Array * Scale + Offset 

I looked at the code and this seems to be the culprit:
https://github.com/areaDetector/ADCore/blob/89a5a2af8126d8476c1d0f6e806a9d62b6c25c7b/ADApp/pluginSrc/NDPluginProcess.cpp#L171C1-L171C63

**Comment by MarkRivers** [comment]
This is a problem with the documentation, not the code.

The description of how AutoOffsetScale works is consistent with the equation Array = (Array + Offset) * Scale, not Array = Array * Scale + Offset.

I will change the documentation in 2 places.

**Comment by MarkRivers** [comment]
The documentation is now fixed:
https://areadetector.github.io/areaDetector/ADCore/NDPluginProcess.html
