### ISSUE TITLE
Remove `documentation` directory?

### ISSUE THREAD

**Issue by ericonr** [areaDetector/ADCore#506]
The [`documentation`](https://github.com/areaDetector/ADCore/tree/master/documentation) directory was last updated in 2020, and seems to have been replaced by the [`docs`](https://github.com/areaDetector/ADCore/tree/master/docs/ADCore) one, but it's still in the ADCore tree. For users of the repository, they could accidentally refer to it and end up using outdated/wrong information, or think some documentation is missing; and for developers, they could accidentally document things in the wrong directory tree.

It seems like removing the tree entirely would help in avoiding issues. A quick grep didn't reveal any references to it, but it would probably be best to confirm.

**Comment by MarkRivers** [comment]
Removed in R3-14.
