### ISSUE TITLE
Confusing documentation in docs/ADCore/plugin_guidelines.rst

### ISSUE THREAD

**Issue by marcomontevechi1** [areaDetector/ADCore#510]
This might be some misunderstanding from my part... I was reading the plugin guidelines and came accross this:
https://github.com/areaDetector/ADCore/blob/621d7d828f5a85c01541d33e0363bc0b8f81c6ef/docs/ADCore/plugin_guidelines.rst?plain=1#L48-L50

However, when searching for the function definition or documentation, I could neither find anything about it in [NDPluginDriver documentation](https://areadetector.github.io/areaDetector/areaDetectorDoxygenHTML/class_n_d_plugin_driver.html) or [asynNDArrayDriver documentation](https://areadetector.github.io/areaDetector/areaDetectorDoxygenHTML/classasyn_n_d_array_driver.html#af2354f73acece6ee2427f5069b16fdb5) nor find any definition of it in the base classes in the source code.

I found only a [call to the function in NDPluginScatter](https://github.com/areaDetector/ADCore/blob/621d7d828f5a85c01541d33e0363bc0b8f81c6ef/ADApp/pluginSrc/NDPluginScatter.cpp#L42), but NDPluginScatter itself [defines the function](https://github.com/areaDetector/ADCore/blob/621d7d828f5a85c01541d33e0363bc0b8f81c6ef/ADApp/pluginSrc/NDPluginScatter.cpp#L59), so it's not called from base classes.

Should this be in documentation? Maybe it was supposed to mean NDPluginDriver::endProcessCallbacks instead of NDPluginDriver::doNDArrayCallbacks() ?

**Comment by MarkRivers** [comment]
Fixed in R3-14
