### ISSUE TITLE
Overlay plugin: "Cross" plotting bug

### ISSUE THREAD

**Issue by anjohnson** [areaDetector/ADCore#54]
Using a git build from last night on darwin-x86 (64 bit), a "Cross" overlay on an RGB1 (Uint8) image doesn't plot the vertical line using the correct RGB colour when the line WidthX setting is >1 – I'm getting the correct color for all the the horizontal line pixels but white pixels for the vertical line, except for the right-most pixel in the vertical line which is coloured correctly. Using size=20 and width=10 for both X and Y for example. The vertical line also drawn incorrectly when using a draw mode of XOR instead of Set and WidthX is >1.

**Comment by MarkRivers** [comment]
Found and fixed this bug.  Pushed new version to master branch.
