### ISSUE TITLE
HDF5 plugin ignores array port

### ISSUE THREAD

**Issue by kmpeters** [areaDetector/ADCore#55]
The HDF5 file-saving plugin ignores the user-specified array port.  Attempts to save just an ROI result in the full frame being saved.  The problem was confirmed on OS X and Windows.  The OS details are below:

Host arch: darwin-x86
areaDetector: 2.0 release
ADCore: 2.0 release
EPICS base: 3.14.12.4
asyn: 4.25

**Comment by MarkRivers** [comment]
Found and fixed this bug.  The problem was that the writeOctet() method was not calling the base class method for parameters that did not belong to the NDFileHDF5 class.  This meant that the new value of NDArrayPort was never being acted upon.
