### ISSUE TITLE
time to delete file: NexusTemplate.xml

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADCore#57]
in ADCore/iocs/simDetectorIOC/iocBoot/iocSimDetector/
the file NexusTemplate.xml is legacy from AD 1.x and can now be deleted

**Comment by MarkRivers** [comment]
Please explain.  AD 2-x still supports the NDFileNexus plugin, and we still want to have an example XML file of how to configure it.

Mark

**Comment by prjemian** [comment]
agreed
