### ISSUE TITLE
NDFileBase.adl needs to be converted to NDFileBase.ui

### ISSUE THREAD

**Issue by ulrikpedersen** [areaDetector/ADCore#89]
@prjemian reported on [issue 66](https://github.com/areaDetector/ADCore/issues/66#issuecomment-83321676)

> also a minor point, since I'm using caQtDM:
> NDFileBase.adl needs to be converted to NDFileBase.ui

I just don't know how that conversion is done...

**Comment by MarkRivers** [comment]
Tim Mooney is planning to do the conversion from .adl to .ui, .opi, and .edl soon.  I spoke to him on Tuesday.

I don't think any adl files in ADCore will change before we release R2-2.

________________________________

**Comment by MarkRivers** [comment]
This was done by @timmmooney yesterday.
